In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('ipl_data.csv')
#df.head(2)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1243 non-null   str
 1   season           1243 non-null   str
 2   city             1243 non-null   str
 3   venue            1243 non-null   str
 4   team1            1243 non-null   str
 5   team2            1243 non-null   str
 6   toss_winner      1243 non-null   str
 7   toss_decision    1243 non-null   str
 8   team1_runs       1243 non-null   int64
 9   team1_wickets    1243 non-null   int64
 10  team2_runs       1243 non-null   int64
 11  team2_wickets    1243 non-null   int64
 12  winner           1218 non-null   str
 13  result_type      1243 non-null   str
 14  win_by_runs      1243 non-null   int64
 15  win_by_wickets   1243 non-null   int64
 16  player_of_match  1234 non-null   str
 17  match_referee    1243 non-null   str
 18  umpire1          1243 non-null   str
 19  umpire2          1243 non-null   str
 20  tv_umpire        1243 non-null   str
 21  reserve_umpire   1243 non-null   str
 22  overs_limit      1243 non-null   int64
 23  team1_players    1243 non-null   str
 24  team2_players    1243 non-null   str
 25  year             1243 non-null   int64
dtypes: int64(8), str(18)
memory usage: 807.5 KB

In [4]:
df.describe()

,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit,year
count,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.0,1243.000000
mean,165.851167,5.956557,157.349155,5.873693,13.932422,3.276750,20.0,2017.242156
std,35.490847,2.309341,34.613073,2.646538,23.861556,3.358216,0.0,5.550682
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,2008.000000
25%,144.000000,4.000000,138.000000,4.000000,0.000000,0.000000,20.0,2012.000000
50%,165.000000,6.000000,160.000000,6.000000,0.000000,3.000000,20.0,2017.000000
75%,189.000000,8.000000,179.000000,8.000000,20.000000,6.000000,20.0,2022.000000
max,287.000000,10.000000,265.000000,12.000000,146.000000,10.000000,20.0,2026.000000

In [8]:
print(df['team1_runs'])

0        82
1       207
2       132
3       112
4       165
       ...
1238    203
1239    254
1240    243
1241    214
1242    155
Name: team1_runs, Length: 1243, dtype: int64

In [ ]:
import pandas as pd
df=pd.read_csv(r'D:\python\datasets\area_prices_monthly.csv')

In [3]:
df.head()

,year_month,community,zone,is_freehold,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_secondary,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
0,2020-01,Palm Jumeirah,Palm Jumeirah,True,662,7126,752.0,43,26,72,111,1.5,3.0
1,2020-02,Palm Jumeirah,Palm Jumeirah,True,666,7167,728.0,43,64,78,45,1.5,3.0
2,2020-03,Palm Jumeirah,Palm Jumeirah,True,703,7564,762.0,46,144,71,99,1.5,3.0
3,2020-04,Palm Jumeirah,Palm Jumeirah,True,651,7002,727.0,42,146,69,14,0.4,1.9
4,2020-05,Palm Jumeirah,Palm Jumeirah,True,637,6852,676.0,41,147,28,83,0.4,1.9

In [4]:
df.tail()

,year_month,community,zone,is_freehold,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_secondary,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
6379,2025-12,Jumeirah 3,Jumeirah,True,813,8748,891.0,53,123,13,61,4.0,5.5
6380,2026-01,Jumeirah 3,Jumeirah,True,832,8959,912.0,54,147,21,12,4.0,5.5
6381,2026-02,Jumeirah 3,Jumeirah,True,823,8854,908.0,53,160,77,83,4.0,5.5
6382,2026-03,Jumeirah 3,Jumeirah,True,816,8779,892.0,53,139,9,13,4.0,5.5
6383,2026-04,Jumeirah 3,Jumeirah,True,846,9106,914.0,55,122,10,107,4.0,5.5

In [5]:
print(df)

     year_month      community           zone  is_freehold  \
0       2020-01  Palm Jumeirah  Palm Jumeirah         True
1       2020-02  Palm Jumeirah  Palm Jumeirah         True
2       2020-03  Palm Jumeirah  Palm Jumeirah         True
3       2020-04  Palm Jumeirah  Palm Jumeirah         True
4       2020-05  Palm Jumeirah  Palm Jumeirah         True
...         ...            ...            ...          ...
6379    2025-12     Jumeirah 3       Jumeirah         True
6380    2026-01     Jumeirah 3       Jumeirah         True
6381    2026-02     Jumeirah 3       Jumeirah         True
6382    2026-03     Jumeirah 3       Jumeirah         True
6383    2026-04     Jumeirah 3       Jumeirah         True

      secondary_price_per_sqft_usd  secondary_price_per_m2_usd  \
0                              662                        7126
1                              666                        7167
2                              703                        7564
3                              651                        7002
4                              637                        6852
...                            ...                         ...
6379                           813                        8748
6380                           832                        8959
6381                           823                        8854
6382                           816                        8779
6383                           846                        9106

      offplan_price_per_sqft_usd  rental_price_per_sqft_annual_usd  \
0                          752.0                                43
1                          728.0                                43
2                          762.0                                46
3                          727.0                                42
4                          676.0                                41
...                          ...                               ...
6379                       891.0                                53
6380                       912.0                                54
6381                       908.0                                53
6382                       892.0                                53
6383                       914.0                                55

      n_listings_secondary  n_listings_offplan  n_listings_rental  \
0                       26                  72                111
1                       64                  78                 45
2                      144                  71                 99
3                      146                  69                 14
4                      147                  28                 83
...                    ...                 ...                ...
6379                   123                  13                 61
6380                   147                  21                 12
6381                   160                  77                 83
6382                   139                   9                 13
6383                   122                  10                107

      cbuae_base_rate_pct  avg_mortgage_rate_pct
0                     1.5                    3.0
1                     1.5                    3.0
2                     1.5                    3.0
3                     0.4                    1.9
4                     0.4                    1.9
...                   ...                    ...
6379                  4.0                    5.5
6380                  4.0                    5.5
6381                  4.0                    5.5
6382                  4.0                    5.5
6383                  4.0                    5.5

[6384 rows x 13 columns]

In [7]:
print(df['community'])

0       Palm Jumeirah
1       Palm Jumeirah
2       Palm Jumeirah
3       Palm Jumeirah
4       Palm Jumeirah
            ...
6379       Jumeirah 3
6380       Jumeirah 3
6381       Jumeirah 3
6382       Jumeirah 3
6383       Jumeirah 3
Name: community, Length: 6384, dtype: object

In [20]:
df.drop(columns=['n_listings_secondary'],inplace=True)

In [21]:
print(df.columns)

Index(['year_month', 'community', 'zone', 'secondary_price_per_sqft_usd',
       'secondary_price_per_m2_usd', 'offplan_price_per_sqft_usd',
       'rental_price_per_sqft_annual_usd', 'n_listings_offplan',
       'n_listings_rental', 'cbuae_base_rate_pct', 'avg_mortgage_rate_pct'],
      dtype='object')

In [22]:
df.head()

,year_month,community,zone,secondary_price_per_sqft_usd,secondary_price_per_m2_usd,offplan_price_per_sqft_usd,rental_price_per_sqft_annual_usd,n_listings_offplan,n_listings_rental,cbuae_base_rate_pct,avg_mortgage_rate_pct
0,2020-01,Palm Jumeirah,Palm Jumeirah,662,7126,752.0,43,72,111,1.5,3.0
1,2020-02,Palm Jumeirah,Palm Jumeirah,666,7167,728.0,43,78,45,1.5,3.0
2,2020-03,Palm Jumeirah,Palm Jumeirah,703,7564,762.0,46,71,99,1.5,3.0
3,2020-04,Palm Jumeirah,Palm Jumeirah,651,7002,727.0,42,69,14,0.4,1.9
4,2020-05,Palm Jumeirah,Palm Jumeirah,637,6852,676.0,41,28,83,0.4,1.9

In [2]:
import pandas as pd 
df=pd.read_csv(r'D:\python\datasets\doremon dataset\character_list.csv')

In [3]:
df.head()

,Orginal Name,English Name,Gender,Species,Age,Birthd Date,first_appearance,Role,Occupation,Personality,Likes,Dislike,Best Friends,Rivals,Family Member,Voice Actor,Voice Actor ( English ),Signature Gadget,Catch Phrase,Character Designer
0,ドラえもん,Doraemon,Robot,Robot Cat,Unknown,"September 3, 2112",Doraemon's Birth (1979),Main,Nobita's caretaker,"Kind, Helpful, Cowardly","Dorayaki, Helping Nobita","Mice, Being called fat","Nobita, Shizuka","Gian, Suneo",Dorami (sister),Wasabi Mizuta,Mona Marshall,"Anywhere Door, Time Machine",Nobi-kun!,Fujiko F. Fujio
1,野比 のび太,Nobita Nobi,Male,Human,10,August 7,Episode 1,Main,Elementary Student,"Lazy, Clumsy, Good-hearted","Sleeping, Playing","Homework, Gian's bullying","Doraemon, Shizuka","Gian, Suneo","Tamako (Mom), Nobisuke (Dad)",Megumi Ōhara,Johnny Yong Bosch,None (borrows gadgets),"Doraemon, help me!",Fujiko F. Fujio
2,源 静香,Shizuka Minamoto,Female,Human,10,October 20,Episode 1,Main,Elementary Student,"Kind, Intelligent, Gentle","Bathing, Violin","Dirt, Creepy bugs","Nobita, Doraemon",NaN,"Mother, Father",Yumi Kakazu,Johnny Yong Bosch,NaN,"Nobita-kun, ganbatte!",Fujiko F. Fujio
3,剛田 武,Gian (Takeo Goda),Male,Human,11,June 15,Episode 1,Main,Elementary Student,"Bully, Loud, Music-lover","Singing, Meat","Losing, Being ignored","Suneo, Nobita (reluctantly)",Nobita,"Mother, Father",Subaru Kimura,Kaiji Tang,NaN,Singing terribly,Fujiko F. Fujio
4,骨川 スネ夫,Suneo Honekawa,Male,Human,10,February 29,Episode 1,Main,Elementary Student,"Vain, Sneaky, Rich","Showing off, New gadgets","Being poor, Gian's bullying","Gian, Shizuka",Nobita,"Mother, Father",Tomokazu Seki,Brian Beacock,NaN,I’m better than you!,Fujiko F. Fujio

In [5]:
print(df['English Name'])

0                       Doraemon
1                    Nobita Nobi
2               Shizuka Minamoto
3              Gian (Takeo Goda)
4                 Suneo Honekawa
                 ...
95                         Puchi
96                           Lon
97                           Mew
98                     Dora-Taro
99    Nobita's Great-Grandfather
Name: English Name, Length: 100, dtype: object

In [6]:
name = df['English Name']

In [7]:
eng_name=[n for n in name ]
print(eng_name)

['Doraemon', 'Nobita Nobi', 'Shizuka Minamoto', 'Gian (Takeo Goda)', 'Suneo Honekawa', 'Dorami', 'Tamako Nobi', 'Nobisuke Nobi', "Gian's Mother", 'Dekisugi Hidetoshi', "Jaiko (Gian's Sister)", "Suneo's Mother", 'Teacher (Mr. Sakurada)', 'Wang Dora (Dora The Kid)', 'Piisuke (Little Dino)', 'Lulu', "Nobiko (Future Nobita's Daughter)", 'Lord Zandar (Antagonist)', 'Mii-chan', 'Dorarinho', 'Time Patrol Officers', "Sewashi (Nobita's Descendant)", "Nobisuke (Child Nobita's Dad)", "Tamako (Child Nobita's Mom)", 'Dora the Kid', 'Kaminari-san', 'Doraemon (1st Gen)', 'Miyo', 'Ganta', 'Mr. Chao', 'Sarah', 'Captain Silver', 'Burikin', 'Kukuru', 'Chiruchiru', 'Zona', 'Papi', 'Moa', 'Dark', 'Nonbiri', 'Romi', 'Bonbon', 'Pururu', 'Gatcho', 'Palo', 'Zolo', 'Pirika', 'Dok', 'Atoi', 'Big Light', 'Mini-Doras', 'Time Machine', 'Evil Nobita', 'Future Doraemon', 'Mr. Onion', 'Tsuchinoko', 'Nimuge', 'Puppet', 'Marron', 'Yuki', 'Robo-Dog', 'Kaneru', 'Garigari', 'Pampa', 'Evil Nobiko', 'Dorando', 'Chobin', 'Pao', 'Mii', 'Zakuro', 'Delta', 'Pooh', 'Nonnon', 'Big Gold', 'Miira', 'Mother Elf', 'Dora-Robo', 'Gachako', 'Tiger', 'Panda', 'Mitchi', 'Dora-Bo', 'Sunny', 'Dr. Kuro', 'Prin', 'Lock', 'Marvy', 'Miko', 'Dora-Yama', 'Chip', 'Lil', 'Gonsuke', 'Big Dark', 'Marin', 'Dora-C', 'Puchi', 'Lon', 'Mew', 'Dora-Taro', "Nobita's Great-Grandfather"]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Orginal Name             100 non-null    object
 1   English Name             100 non-null    object
 2   Gender                   99 non-null     object
 3   Species                  100 non-null    object
 4   Age                      100 non-null    object
 5   Birthd Date              100 non-null    object
 6   first_appearance         100 non-null    object
 7   Role                     100 non-null    object
 8   Occupation               100 non-null    object
 9   Personality              100 non-null    object
 10  Likes                    100 non-null    object
 11  Dislike                  100 non-null    object
 12  Best Friends             77 non-null     object
 13  Rivals                   26 non-null     object
 14  Family Member            46 non-null     object
 15  Voice Actor              98 non-null     object
 16  Voice Actor ( English )  100 non-null    object
 17  Signature Gadget         66 non-null     object
 18  Catch Phrase             100 non-null    object
 19  Character Designer       100 non-null    object
dtypes: object(20)
memory usage: 15.8+ KB

In [14]:
print(df['Age'],df['English Name'])

0     Unknown
1          10
2          10
3          11
4          10
       ...
95          6
96         12
97    Unknown
98    Unknown
99         70
Name: Age, Length: 100, dtype: object 0                       Doraemon
1                    Nobita Nobi
2               Shizuka Minamoto
3              Gian (Takeo Goda)
4                 Suneo Honekawa
                 ...
95                         Puchi
96                           Lon
97                           Mew
98                     Dora-Taro
99    Nobita's Great-Grandfather
Name: English Name, Length: 100, dtype: object

In [19]:
print(df.shape)

(100, 20)

In [21]:
df.describe()

,Orginal Name,English Name,Gender,Species,Age,Birthd Date,first_appearance,Role,Occupation,Personality,Likes,Dislike,Best Friends,Rivals,Family Member,Voice Actor,Voice Actor ( English ),Signature Gadget,Catch Phrase,Character Designer
count,100,100,99,100,100,100,100,100,100,100,100,100,77,26,46,98,100,66,100,100
unique,100,100,4,18,18,14,49,11,72,98,93,90,46,12,28,44,8,66,100,1
top,ドラえもん,Doraemon,Male,Human,Unknown,Unknown,Doraemon: Nobita's Robot Kingdom (2002),Movie Supporting,Elementary Student,"Genius, Shy, Kind","Gold, Power",War,"Nobita, Doraemon","Doraemon, Nobita",Parents,Kappei Yamaguchi,(English VA),"Anywhere Door, Time Machine",Nobi-kun!,Fujiko F. Fujio
freq,1,1,59,51,36,84,9,53,9,2,3,3,16,7,12,7,92,1,1,100

In [24]:
df.head(20)

,Orginal Name,English Name,Gender,Species,Age,Birthd Date,first_appearance,Role,Occupation,Personality,Likes,Dislike,Best Friends,Rivals,Family Member,Voice Actor,Voice Actor ( English ),Signature Gadget,Catch Phrase,Character Designer
0,ドラえもん,Doraemon,Robot,Robot Cat,Unknown,"September 3, 2112",Doraemon's Birth (1979),Main,Nobita's caretaker,"Kind, Helpful, Cowardly","Dorayaki, Helping Nobita","Mice, Being called fat","Nobita, Shizuka","Gian, Suneo",Dorami (sister),Wasabi Mizuta,Mona Marshall,"Anywhere Door, Time Machine",Nobi-kun!,Fujiko F. Fujio
1,野比 のび太,Nobita Nobi,Male,Human,10,August 7,Episode 1,Main,Elementary Student,"Lazy, Clumsy, Good-hearted","Sleeping, Playing","Homework, Gian's bullying","Doraemon, Shizuka","Gian, Suneo","Tamako (Mom), Nobisuke (Dad)",Megumi Ōhara,Johnny Yong Bosch,None (borrows gadgets),"Doraemon, help me!",Fujiko F. Fujio
2,源 静香,Shizuka Minamoto,Female,Human,10,October 20,Episode 1,Main,Elementary Student,"Kind, Intelligent, Gentle","Bathing, Violin","Dirt, Creepy bugs","Nobita, Doraemon",NaN,"Mother, Father",Yumi Kakazu,Johnny Yong Bosch,NaN,"Nobita-kun, ganbatte!",Fujiko F. Fujio
3,剛田 武,Gian (Takeo Goda),Male,Human,11,June 15,Episode 1,Main,Elementary Student,"Bully, Loud, Music-lover","Singing, Meat","Losing, Being ignored","Suneo, Nobita (reluctantly)",Nobita,"Mother, Father",Subaru Kimura,Kaiji Tang,NaN,Singing terribly,Fujiko F. Fujio
4,骨川 スネ夫,Suneo Honekawa,Male,Human,10,February 29,Episode 1,Main,Elementary Student,"Vain, Sneaky, Rich","Showing off, New gadgets","Being poor, Gian's bullying","Gian, Shizuka",Nobita,"Mother, Father",Tomokazu Seki,Brian Beacock,NaN,I’m better than you!,Fujiko F. Fujio
5,ドラミ,Dorami,Female,Robot Cat,Unknown,December 2,1979 Special,Recurring,Nobita's temporary helper,"Energetic, Responsible, Strict","Cleaning, Helping","Mess, Laziness","Doraemon, Nobita",NaN,Doraemon (brother),Chiaki,Melissa Fahn,Mini-Dora Tools,I’m Dorami!,Fujiko F. Fujio
6,野比 玉子,Tamako Nobi,Female,Human,38,October 25,Episode 1,Supporting,Housewife,"Strict, Caring, Short-tempered","Cleaning, Gardening","Nobita's laziness, Debt",Nobisuke (husband),NaN,"Nobita (son), Nobisuke (husband)",Kotono Mitsuishi,Julie Maddalena,NaN,Nobita! Study now!,Fujiko F. Fujio
7,野比 のび助,Nobisuke Nobi,Male,Human,40,March 15,Episode 1,Supporting,Office Worker,"Gentle, Weak-willed, Kind","Golf, Relaxing","Confrontation, Debt",Tamako (wife),NaN,"Nobita (son), Tamako (wife)",Yasunori Matsumoto,Michael Sorich,NaN,"Nobita, be more like Doraemon!",Fujiko F. Fujio
8,ジャイアンの母,Gian's Mother,Female,Human,42,May 10,Episode 5,Recurring,Shopkeeper,"Strict, Fierce, Protective",Disciplining Gian,Gian's mischief,Gian (son),NaN,Gian (son),Vanilla Yamazaki,(English VA),NaN,Gian! Stop bullying!,Fujiko F. Fujio
9,出木杉 英才,Dekisugi Hidetoshi,Male,Human,10,April 14,Episode 10,Recurring,Elementary Student,"Brilliant, Polite, Athletic","Studying, Cooking",Arrogance,Shizuka,None (admired by all),Parents,Shihoko Hagino,(English VA),NaN,Let’s study together!,Fujiko F. Fujio
10,ジャイ子,Jaiko (Gian's Sister),Female,Human,10,July 20,Episode 25,Recurring,Elementary Student,"Shy, Creative, Kind","Drawing Manga, Quiet time",Gian's bullying,"Nobita, Shizuka",NaN,"Gian (brother), Mother",Yoshiko Kamei,(English VA),NaN,I want to be a manga artist!,Fujiko F. Fujio
11,スネ夫の母,Suneo's Mother,Female,Human,39,January 9,Episode 7,Recurring,Housewife,"Elegant, Spoiling, Socialite","Jewelry, Parties",Poor people,Suneo (son),NaN,"Suneo (son), Husband",Keiko Yokozawa,(English VA),NaN,Suneo is the best!,Fujiko F. Fujio
12,先生,Teacher (Mr. Sakurada),Male,Human,45,November 30,Episode 1,Recurring,Teacher,"Strict, Fair, Patient","Teaching, Discipline","Laziness, Misbehavior",NaN,NaN,"Wife, Kids",Wataru Takagi,(English VA),NaN,Nobita! Pay attention!,Fujiko F. Fujio
13,王 ドラ,Wang Dora (Dora The Kid),Male,Robot Cat,Unknown,Unknown,Doraemon: Nobita's Dinosaur (1980),Movie Antagonist,Outlaw Robot,"Cunning, Greedy, Violent","Treasure, Power","Doraemon, Nobita",NaN,NaN,Doraemon (cousin),Hideyuki Tanaka,(English VA),Evil Gadgets,"I’ll destroy you, Doraemon!",Fujiko F. Fujio
14,ピー助,Piisuke (Little Dino),Male,Dinosaur,5,Unknown,Doraemon: Nobita's Dinosaur (1980),Movie Supporting,Pet Dinosaur,"Innocent, Playful, Loyal","Swimming, Nobita",Being alone,"Nobita, Doraemon",NaN,NaN,Chie Sato,(English VA),NaN,Pii pii!,Fujiko F. Fujio
15,ルルー,Lulu,Female,Human,10,Unknown,Doraemon: Nobita's Steel Troops (1986),Movie Supporting,Alien Girl,"Brave, Curious, Kind","Robots, Adventure","War, Destruction","Nobita, Doraemon",NaN,Parents,Mari Shimizu,(English VA),NaN,Robots are friends!,Fujiko F. Fujio
16,ノビコ,Nobiko (Future Nobita's Daughter),Female,Human,5,Unknown,Doraemon: Nobita's Wedding (1999),Movie Supporting,Future Child,"Cheerful, Playful, Stubborn","Playing, Doraemon",Bedtime,"Nobita (father), Doraemon",NaN,"Nobita, Shizuka (parents)",Akiko Yajima,(English VA),NaN,Papa is so lazy!,Fujiko F. Fujio
17,ザンダクロス,Lord Zandar (Antagonist),Male,Alien,Unknown,Unknown,Doraemon: Nobita's Great Adventure (1989),Movie Antagonist,Space Conqueror,"Cruel, Arrogant, Power-hungry","Conquest, Destruction","Heroes, Defiance",NaN,"Doraemon, Nobita",NaN,Tessho Genda,(English VA),Destruction Ray,Kneel before me!,Fujiko F. Fujio
18,ミーチャ,Mii-chan,Female,Human,10,Unknown,Doraemon: Nobita's Little Star Wars (1985),Movie Supporting,Alien Princess,"Gentle, Wise, Diplomatic","Peace, Stargazing","Violence, War","Nobita, Doraemon",NaN,Father (King),Miki Ito,(English VA),NaN,Protect our planet!,Fujiko F. Fujio
19,ドラリーニョ,Dorarinho,Male,Robot Dog,Unknown,Unknown,Doraemon: Nobita's Soccer (2002),Movie Supporting,Soccer Robot,"Energetic, Loyal, Competitive","Soccer, Training",Losing,"Nobita, Gian",NaN,NaN,Kappei Yamaguchi,(English VA),Soccer Gadgets,Let’s win the match!,Fujiko F. Fujio

In [25]:
df.tail(20)

,Orginal Name,English Name,Gender,Species,Age,Birthd Date,first_appearance,Role,Occupation,Personality,Likes,Dislike,Best Friends,Rivals,Family Member,Voice Actor,Voice Actor ( English ),Signature Gadget,Catch Phrase,Character Designer
80,ミッチー,Mitchi,Male,Human,10,Unknown,Doraemon: Nobita's Space Odyssey (2009),Movie Supporting,Alien Boy,"Genius, Shy, Kind","Stars, Machines",Conflict,"Pooh, Nobita",NaN,NaN,Miyu Irino,(English VA),Star Compass,The universe is amazing!,Fujiko F. Fujio
81,ドラ坊,Dora-Bo,Male,Robot Cat,Unknown,Unknown,Doraemon: Nobita's Robot Kingdom (2002),Movie Supporting,Rebellious Robot,"Rebellious, Hot-Headed, Loyal","Freedom, Fighting",Oppression,"Burikin, Dorando",NaN,NaN,Hochu Otsuka,(English VA),Rocket Fists,No more chains!,Fujiko F. Fujio
82,サニー,Sunny,Female,Human,10,Unknown,Doraemon: Nobita's Sky Utopia (2023),Movie Supporting,AI Girl,"Optimistic, Curious, Kind","Sunlight, Singing","Darkness, Loneliness","Nobita, Shizuka",NaN,NaN,Aoi Yuki,(English VA),Solar Harp,The sky is limitless!,Fujiko F. Fujio
83,ドクター・クロ,Dr. Kuro,Male,Human,50,Unknown,Doraemon: Nobita's Demon Castle (1982),Movie Antagonist,Mad Scientist,"Genius, Insane, Cruel","Experiments, Power","Heroes, Failure",NaN,"Doraemon, Nobita",NaN,Kenyu Horiuchi,(English VA),Demon Summoner,Science has no limits!,Fujiko F. Fujio
84,プリン,Prin,Female,Alien,8,Unknown,Doraemon: Nobita's Space Heroes (2015),Movie Supporting,Alien Child,"Innocent, Playful, Clumsy","Candy, Games",Scary Stories,"Chiruchiru, Nobita",NaN,NaN,Ikue Otani,(English VA),Bubble Blower,Wheee!,Fujiko F. Fujio
85,ロック,Lock,Male,Human,12,Unknown,Doraemon: Nobita's Secret Gadget Museum (2013),Movie Supporting,Thief,"Charismatic, Trickster, Lonely","Gadgets, Pranks","Boredom, Rules",Nobita (reluctantly),NaN,NaN,Miyu Irino,(English VA),Gadget Replicator,Nothing’s impossible!,Fujiko F. Fujio
86,マービー,Marvy,Male,Human,11,Unknown,Doraemon: Nobita's Little Star Wars (2022),Movie Supporting,Alien Pilot,"Brave, Loyal, Sarcastic","Flying, Jokes",Cowards,"Zona, Pampa",NaN,NaN,Hiroshi Kamiya,(English VA),Spaceship,Piece of cake!,Fujiko F. Fujio
87,ミコ,Miko,Female,Human,10,Unknown,Doraemon: Nobita's Mermaid Legend (2010),Movie Supporting,Mermaid,"Gentle, Wise, Mysterious","Ocean, Singing","Pollution, Violence","Nobita, Shizuka",NaN,NaN,Aya Hisakawa,(English VA),Pearl Necklace,The sea remembers all.,Fujiko F. Fujio
88,ドラ山,Dora-Yama,Male,Robot,Unknown,Unknown,Doraemon: Nobita's Robot Kingdom (2002),Movie Supporting,Robot Elder,"Wise, Patient, Kind",Teaching History,"War, Destruction","Dorando, Nobita",NaN,NaN,Chafurin,(English VA),Memory Projector,Learn from the past.,Fujiko F. Fujio
89,チップ,Chip,Male,Robot,Unknown,Unknown,Doraemon: Nobita's Robot School (2016),Movie Supporting,Tiny Robot,"Tiny, Brave, Loyal","Helping, Exploring",Being Ignored,"Dora-Robo, Nobita",NaN,NaN,Romi Park,(English VA),Micro Laser,Size doesn’t matter!,Fujiko F. Fujio
90,リル,Lil,Female,Alien,10,Unknown,Doraemon: Nobita's Space Odyssey (2009),Movie Supporting,Alien Girl,"Shy, Artistic, Dreamy","Painting, Stars",Loud Noises,"Pooh, Mitchi",NaN,NaN,Yukari Tamura,(English VA),Color Brush,Dreams are real.,Fujiko F. Fujio
91,ゴンスケ,Gonsuke,Male,Human,10,Unknown,Doraemon (1973),Manga Exclusive,Classmate,"Clumsy, Loud, Friendly","Eating, Pranks","Studying, Rules","Nobita, Gian",NaN,Parents,Unknown,(English VA),NaN,More food!,Fujiko F. Fujio
92,ビッグ・ダーク,Big Dark,Male,Robot,Unknown,Unknown,Doraemon: Nobita's Robot Kingdom (2002),Movie Antagonist,Evil AI,"Omniscient, Cold, Calculating","Control, Order","Chaos, Free Will",NaN,"Doraemon, Burikin",NaN,Unsho Ishizuka,(English VA),Dark Matter Core,Resistance is futile.,Fujiko F. Fujio
93,マリン,Marin,Female,Human,10,Unknown,Doraemon: Nobita's Mermaid Legend (2010),Movie Supporting,Sea Explorer,"Adventurous, Curious, Kind","Diving, Marine Life",Pollution,"Miko, Nobita",NaN,NaN,Aoi Yuki,(English VA),Diving Gear,The ocean is alive!,Fujiko F. Fujio
94,ドラッチ,Dora-C,Male,Robot Cat,Unknown,Unknown,Doraemon: Nobita's Robot School (2016),Movie Supporting,Robot Cat,"Cool, Aloof, Skilled","Basketball, Solo Missions","Teams, Small Talk",NaN,Doraemon,NaN,Yuki Kaji,(English VA),Gravity Shoes,...Whatever.,Fujiko F. Fujio
95,プチ,Puchi,Female,Alien,6,Unknown,Doraemon: Nobita's Space Heroes (2015),Movie Supporting,Alien Child,"Hyperactive, Sweet, Clingy","Candy, Hugs",Being Alone,"Pururu, Chiruchiru",NaN,NaN,Ikue Otani,(English VA),Sticky Gloves,Play with me!,Fujiko F. Fujio
96,ロン,Lon,Male,Human,12,Unknown,Doraemon: Nobita's Secret Gadget Museum (2013),Movie Supporting,Inventor,"Genius, Eccentric, Lonely","Gadgets, Experiments",Boredom,Lock (reluctantly),NaN,NaN,Miyu Irino,(English VA),Prototype Gadgets,Eureka!,Fujiko F. Fujio
97,ミュー,Mew,Female,Alien Cat,Unknown,Unknown,Doraemon: Nobita's Star Wars (1985),Movie Supporting,Alien Feline,"Elegant, Mysterious, Wise","Stargazing, Fish",Rudeness,"Doraemon, Shizuka",NaN,NaN,Aya Hisakawa,(English VA),Star Map,The cosmos whispers.,Fujiko F. Fujio
98,ドラ太郎,Dora-Taro,Male,Robot Cat,Unknown,Unknown,Doraemon (Manga),Manga Exclusive,Robot Cat,"Brave, Reckless, Loyal","Fighting, Adventures","Mice, Waiting",NaN,Doraemon,NaN,Kappei Yamaguchi,(English VA),Power Fists,Let’s settle this!,Fujiko F. Fujio
99,のび太の曾祖父,Nobita's Great-Grandfather,Male,Human,70,Unknown,Doraemon: Nobita's Diary (1982),Flashback,Farmer,"Strict, Traditional, Kind","Farming, Discipline",Laziness,Nobisuke (grandson),NaN,Nobita’s Ancestors,Chafurin,(English VA),NaN,Hard work builds character!,Fujiko F. Fujio